/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseExp: typeof import('./src/components/lsDialog/lsDialogTest/BaseExp.vue')['default']
    BodyExp: typeof import('./src/components/lsDialog/lsDialogTest/BodyExp.vue')['default']
    CloseExp: typeof import('./src/components/lsDialog/lsDialogTest/CloseExp.vue')['default']
    DynamicHeightVirtualList: typeof import('./src/components/dynamicHeightVirtualList/DynamicHeightVirtualList.vue')['default']
    DynamicHeightVirtualListTest: typeof import('./src/components/dynamicHeightVirtualList/DynamicHeightVirtualListTest.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ExampleBox: typeof import('./src/components/exampleBox/ExampleBox.vue')['default']
    ExpandableBox: typeof import('./src/components/expandableBox/ExpandableBox.vue')['default']
    ExpandableBoxTest: typeof import('./src/components/expandableBox/ExpandableBoxTest.vue')['default']
    FooterExp: typeof import('./src/components/lsDialog/lsDialogTest/FooterExp.vue')['default']
    FullScreenExp: typeof import('./src/components/lsDialog/lsDialogTest/FullScreenExp.vue')['default']
    LsDialog: typeof import('./src/components/lsDialog/LsDialog.vue')['default']
    LsDialogPanel: typeof import('./src/components/lsDialog/LsDialogPanel.vue')['default']
    LsDialogTest: typeof import('./src/components/lsDialog/LsDialogTest.vue')['default']
    ModalExp: typeof import('./src/components/lsDialog/lsDialogTest/ModalExp.vue')['default']
    PositionExp: typeof import('./src/components/lsDialog/lsDialogTest/PositionExp.vue')['default']
    RollNumber: typeof import('./src/components/rollNumber/RollNumber.vue')['default']
    RollNumberTest: typeof import('./src/components/rollNumber/RollNumberTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualList: typeof import('./src/components/virtualList/VirtualList.vue')['default']
    VirtualListTest: typeof import('./src/components/virtualList/VirtualListTest.vue')['default']
    VuePlayground: typeof import('./src/components/vuePlayground/VuePlayground.vue')['default']
    WidthHighExp: typeof import('./src/components/lsDialog/lsDialogTest/WidthHighExp.vue')['default']
  }
}
